name: Testing

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.138.0
        with:
          ruby-version: 3.2
      - run: bundle install
      - name: Precompile assets
        run: bundle exec rake assets:precompile
      - name: Run Tests
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
          OPEN_WEATHER_API_KEY: $OPEN_WEATHER_API_KEY
        run: |
          bin/rails db:setup
          bundle exec rake test